The-Legion-Preservation-Project/LegionCore-7.3.5

- src/server/game/Handlers/CharacterHandler.cpp
- src/server/game/Server/WorldSession.cpp
- src/server/game/Server/WorldSession.h
- src/server/game/Server/WorldSocket.cpp
This was poorly written and effectively locked a user out of the worldserver permanently if they back out of the character creation screen.
> prevent char enum lockout

- src/server/bnetserver/Server/Session.cpp
- src/server/database/Database/Implementation/LoginDatabase.cpp
It's hard to get reconnected when your last played character is on an offline realm; this filters last played characters results so they don't include offline realms. In this case, you'll see the realm selection after login.
> Core/Bnet: don't return last played when realm is offline

- src/server/game/Chat/Chat.cpp
- src/server/game/Chat/Chat.h
- src/server/scripts/Commands/cs_list.cpp
- src/server/scripts/Commands/cs_lookup.cpp
- src/server/scripts/Commands/cs_npc.cpp
`LANG_QUEST_LIST_CHAT` was formatted with the wrong number of arguments for this core.
Also updated `Chat::PGetParseString`.
> Core/Scripts: fix lookup quest command crash

- sql/updates/world/2024_10_29_smart_event_expansion.sql
- src/server/game/AI/SmartScripts/SmartScript.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.h
This moves the LC-specific smart events to higher numbers so (in the future) we can merge the TC events that use those numbers. This will also make it easier to port scripts from future database versions.
> Core/SAI: make room for new TC smart events

- sql/updates/world/2024_10_31_smart_script_offer_quest.sql
- src/server/game/AI/SmartScripts/SmartScript.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.h
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Player/Player.h
- src/server/game/Handlers/QuestHandler.cpp
- src/server/game/Spells/SpellEffects.cpp
This fixes multiple issues with the quest system.
SMART_ACTION_ADD_QUEST -> SMART_ACTION_OFFER_QUEST from https://github.com/TrinityCore/TrinityCore/commit/573cb9d20f01bdc6dce8763aa9affa9ed2ae3679
- This updates the smart script system to offer quests via popup rather than adding straight to the quest log. The old behavior is maintained for all quests except the one that I tested https://www.wowhead.com/quest=27697/corruption-in-maraudon which is offered via area trigger when you first enter the instance.
- Area trigger quest push (using SMART_ACTION_OFFER_QUEST) has also been updated to only offer quests that have NOT already been completed, when `directAdd` is not used.
Fix follow up popup quests from https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/4f23fb3d29fc8f …
> Core/Quests: fix area trigger quest push and quest chain popup

- src/common/Utilities/Timer.h
- src/common/Utilities/WowTime.cpp
- src/common/Utilities/WowTime.hpp
- src/server/game/Calendar/CalendarMgr.cpp
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Handlers/CharacterHandler.cpp
- src/server/game/Server/Packets/AchievementPackets.cpp
- src/server/game/Server/Packets/BattlePetPackets.cpp
- src/server/game/Server/Packets/CalendarPackets.cpp
- src/server/game/Server/Packets/ChallengeModePackets.cpp
- src/server/game/Server/Packets/GuildPackets.cpp
- src/server/game/Server/Packets/MiscPackets.cpp
- src/server/game/Server/Packets/PacketUtilities.h
- src/server/game/Server/WorldSocket.h
- src/server/game/Time/GameTime.cpp
- src/server/game/Time/GameTime.h
This fixes the in-game day/night cycle to match local time (instead of always being UTC).
Fixes https://github.com/The-Legion-Preservation-Project/LegionCore-7.3.5/issues/93
> Core/PacketIO: use local time in packets instead of UTC

- sql/updates/world/2024_11_01_fix_spell_visual_kit.sql
- src/server/game/AI/SmartScripts/SmartScript.cpp
- src/server/game/AI/SmartScripts/SmartScriptMgr.h
- src/server/game/Server/Packets/SpellPackets.cpp
- src/server/scripts/Legion/AntorusTheBurningThrone/boss_varimathras.cpp
- src/server/scripts/Legion/MawofSouls/boss_helya.cpp
- src/server/scripts/Legion/MicroHolidays/MoonkinFestival.cpp
- src/server/scripts/Legion/TheEmeraldNightmare/boss_cenarius.cpp
- src/server/scripts/Legion/TheNighthold/boss_skorpyron.cpp
- src/server/scripts/Legion/TheNighthold/boss_tichondrius.cpp
- src/server/scripts/Legion/TombOfSargeras/boss_TheDesolateHost.cpp
- src/server/scripts/Legion/VioletHoldLegion/boss_millificent_manastorm.cpp
- src/server/scripts/Scenario/Artifacts/Paladin/BrokenShore/broken_shore.cpp
- src/server/scripts/Spells/spell_item.cpp
- src/server/scripts/Spells/spell_paladin.cpp
The core was incorrectly using kit type instead of kit rec id/spellVisualKitId, which explains the incorrect packet order.
- Packet order has been fixed.
- All calls to `SendPlaySpellVisualKit` have been updated to properly pass spellVisualKitId.
- Verify with paladin spell https://www.wowhead.com/spell=53385/divine-storm
- `smart_scripts` table data has been updated so `SMART_ACTION_PLAY_SPELL_VISUAL_KIT` uses spellVisualKitId instead of kitType.
- `.go c 14525514` https://www.wowhead.com/npc=88859/elya-azuremoon
- `.gm on`
- select dialog option to see spell visual kit
- `spell_visual_kit` table data has been updated to use `KitRecID` instead of `KitType`.
- verify with `.cast 181765` - player will briefly raise hand
> Core: fix spell visual kit system

- src/server/game/Entities/Pet/Pet.h
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Entities/Unit/Unit.h
* added `CanCastSpellWhileMoving` check.
* pet should now stay in place while casting.
> Core/Pets: CanCastSpellWhileMoving check

- src/server/game/AI/CoreAI/GameObjectAI.h
- src/server/game/AI/SmartScripts/SmartAI.cpp
- src/server/game/AI/SmartScripts/SmartAI.h
- src/server/game/Entities/GameObject/GameObject.cpp
- src/server/game/Entities/GameObject/GameObject.h
- src/server/game/Handlers/SpellHandler.cpp
- src/server/game/Spells/SpellEffects.cpp
- src/server/scripts/Draenor/dark_portal.cpp
- src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
- src/server/scripts/Legion/mardum.cpp
- src/server/scripts/Legion/warden_prison.cpp
- src/server/scripts/Northrend/ChamberOfAspects/RubySanctum/boss_halion.cpp
- src/server/scripts/Northrend/Ulduar/Ulduar/boss_algalon_the_observer.cpp
- src/server/scripts/Scenario/Artifacts/DemonHunter/Vengeance/DH_vengeance_art_scenario.cpp
- src/server/scripts/Scenario/Artifacts/Monk/Shey-lun/Sheylun.cpp
- src/server/scripts/Scenario/Artifacts/Priest/Tuure/Tuure.cpp
- src/server/scripts/Scenario/Artifacts/Rogue/FangsoftheDevourer/Devourer.cpp
- src/server/scripts/Scenario/Artifacts/Rogue/Kingslayers/Kingslayers.cpp
- src/server/scripts/Scenario/Artifacts/Warrior/Warswords/Warswords.cpp
- src/server/scripts/Scenario/AssaultBrokenShore/AssaultBrokenShore.cpp
- src/server/scripts/World/go_scripts.cpp
- From https://github.com/TrinityCore/TrinityCore/commit/8a3f053a2f82460cf5d856404f6fcaf4b7eb44aa
- Reset game object to original state from DB instead of toggling from whatever current state we have
- From https://github.com/TrinityCore/TrinityCore/commit/b539ac6afafbddcb75855511d66d97bbc2e95c30
- Add `isUse` param to game object gossip hello to disambiguate `CMSG_GAME_OBJ_REPORT_USE` and `CMSG_GAME_OBJ_USE`
- This makes unlocking the soul prison no longer an instant cast - now you can actually see the cast bar for https://www.wowhead.com/spell=54669/unlocking-soul-prison
Closes #133 
- All Acherus Soul Prison tooltips now correctly show the key name
- Unlocking a soul prison requires the key
- The unlock spell is properly …
> Core/GameObject: reset to spawn game object state and fix interaction

- sql/updates/world/2024_11_03_fix_eye_of_acherus_flight.sql
- src/server/game/Anticheat/Anticheat.cpp
- src/server/game/Entities/Creature/Creature.cpp
- src/server/game/Entities/Creature/CreatureData.h
- src/server/game/Entities/Object/Object.h
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Player/Player.h
- src/server/game/Entities/Unit/CharmInfo.cpp
- src/server/game/Entities/Unit/CharmInfo.h
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Entities/Unit/Unit.h
- src/server/game/Handlers/ItemHandler.cpp
- src/server/game/Handlers/MovementHandler.cpp
- src/server/game/Handlers/PetHandler.cpp
- src/server/game/Handlers/SpellHandler.cpp
- src/server/game/Movement/MotionMaster.cpp
- src/server/game/Movement/MotionMaster.h
- src/server/game/Movement/MovementGenerators/GenericMovementGenerator.cpp
- src/server/game/Movement/MovementGenerators/GenericMovementGenerator.h
- src/server/game/Spells/Auras/SpellAuraEffects.cpp
- src/server/game/Spells/SpellEffects.cpp
- src/server/scripts/EasternKingdoms/ScarletEnclave/chapter1.cpp
- src/server/scripts/Spells/spell_quest.cpp
- Goal was to improve movement in https://www.wowhead.com/quest=12641/death-comes-from-on-high
- `npc_eye_of_acherus` script ported from TC master
- Cleanup around client control/possession
- Enable flying
- Fix action bar buttons/order
- Fix recall spell on action bar
- Use spell script for siphon credit
- References
- https://github.com/TrinityCore/TrinityCore/commit/bba4696de715b79b31e154d1a8e1597507812ece
- https://github.com/TrinityCore/TrinityCore/commit/edc75831194bc2419e3abada47121fadf4b2aa8d
- https://github.com/TrinityCore/TrinityCore/commit/b1721a65ee7595b99269d01cdccd7aa6557ab099
- https://github.com/TrinityCore/TrinityCore/commit/eccb0ed3dac67a7463cc5c1ff5cf2cd3919e7a25
(Does it build, tested in-game, etc.) …
> Core/Quest: Death Comes from On High (part 1)

- src/server/game/Spells/Spell.cpp
- Spell damage will now be dealt before starting combat
- This prevents dead creatures from calling for assistance, like on quest https://www.wowhead.com/quest=12701/massacre-at-lights-point
none
tested in-game
none
> Core/Spells: start combat after dealing spell damage

- sql/updates/world/2024_11_04_death_knight_spell_scripts.sql
- src/server/game/Entities/Player/Player.h
- src/server/game/Spells/Spell.cpp
- src/server/game/Spells/SpellEffects.cpp
- src/server/scripts/Spells/spell_dk.cpp
- Moves some DK spells into spell scripts
- https://www.wowhead.com/spell=49998/death-strike
- https://www.wowhead.com/spell=50842/blood-boil
- https://www.wowhead.com/spell=43265/death-and-decay
- Cleans up a couple other DK spell scripts
- Fixes regression with spell effect radius
tested in-game
none
> Core/Spells: improve and cleanup some dk spell scripts

- src/server/game/Spells/Spell.cpp
Never fail mining, herbing, skinning. From patch notes:
> Patch 3.1.0 (2009-04-14): You can no longer fail when Mining, Herbing, and Skinning.
none
tested in-game
none
> [Core/Gathering] Never fail mining, herbing, skinning attempts

- src/server/game/AuctionHouseBot/AuctionHouseBotSeller.cpp
AHBot seller was incorrectly ignoring stack size when pricing items with market data. This fixes so market price is multiplied by stack size.
none
tested in-game
none
> Core/AHBot: fix seller pricing on items with market data

- src/server/game/Pools/PoolMgr.cpp
- Missing brackets caused unreachable code in mother pool loading; this has been fixed and mother pools work again
none
tested in-game (cobalt nodes in northrend)
none
> Core/Pools: fix loading mother pools

- src/server/game/Spells/SpellMgr.cpp
- This fixes summon properties 121 to use SUMMON_TYPE_TOTEM so it doesn't chase and attack the player
- Used by https://www.wowhead.com/spell=34980/mennus-healing-ward
none
tested in-game; TC has similar fix
none
> Core/Summon: fix summon properties 121 SUMMON_TYPE_TOTEM

- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Spells/Auras/SpellAuraEffects.cpp
- src/server/game/Spells/Spell.cpp
- DK Asphyxiate spell https://www.wowhead.com/spell=221562/asphyxiate causes creatures to evade
- This fixes the strangulate aura effect so that it properly toggles disable gravity
- Now creatures can be attacked during and after asphyxiate
none
tested in-game
none
> Core/Spells: fix strangulate aura effect

- src/server/game/Entities/Player/Player.cpp
- Fixes regression when looting items like https://www.wowhead.com/item=24476/jaggal-clam
- Regression was caused by #145 
none
tested in-game
none
> Core/Loot: fix regression in Player::AutoStoreLoot

- src/server/game/Spells/SpellEffects.cpp
- Fixes charge effect without pre-generated path, specifically https://www.wowhead.com/wotlk/spell=54878/merge
none
tested in-game
none
> Core/Spells: fix spell effect charge

- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Player/Player.h
- src/server/game/Spells/SpellEffects.cpp
- Previously, gathering XP was always reduced by 90%
- Now, it scales down based on player level compared to chest/gathering node "xp level"
- Formula is based on https://wowwiki-archive.fandom.com/wiki/Formulas:Gather_XP#XP_modification_based_on_character_Level
> Character_level  = Item_Level + 2 : (94.8%)   (Character lower level than gather level)
Character_level  = Item_Level + 1 : (97.4%)
Character_level <= Item_Level + 0 : (100%)    (Character level close to gather level)
Character_level >= Item_Level - 5 : (100%)    
Character_level  = Item_Level - 6 :  (80%)    (Character level exceeds gather level)
Character_level  = Item_Level - 7 :  (60%)
Character_level  = Item_Level - 8 :  (40%)
Character_level  = Item_Level - 8 :  (40%)
Character_level <= Item_Level - …
> Core/Gathering: update gathering xp calculation

- src/server/game/Entities/Player/Player.cpp
- Specialization spells, like https://www.wowhead.com/spell=51886/cleanse-spirit need to be learned before action bars are loaded
- This fixes items disappearing from action bars on login
none
tested in-game
none
> Core/Player: fix loading action bar spells

- src/server/game/Quests/QuestDef.cpp
- This removes ~90% XP penalty for completing quests in "old expansions"
- Quest XP is already reduced by diff between player level and max quest level
none
tested in-game
none
> Core/Scaling: remove quest xp expansion penalty

- src/server/game/Entities/AreaTrigger/AreaTrigger.cpp
- src/server/game/Entities/Creature/CreatureGroups.cpp
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Maps/Map.cpp
- src/server/game/Server/WorldSession.cpp
- src/server/game/Spells/Auras/SpellAuraEffects.cpp
- src/server/game/Spells/Auras/SpellAuras.cpp
- src/server/game/Spells/Spell.cpp
- src/server/game/Spells/SpellEffects.cpp
- src/server/scripts/Legion/TheNighthold/instance_the_nighthold.cpp
- Removes some weird `#ifdef WIN32` blocks around logging
- Also switches `#ifdef WIN32` blocks around `DebugVisualizePolygon()` and `DebugVisualizePosition()` and replaces with `#ifdef TRINITY_DEBUG
- This fixes the issue where unexpected training dummies would spawn for all Windows servers :roll_eyes: 
none
tested in-game
none
> Core/Misc: remove win32-specific logging

- sql/updates/world/2024_11_21_fix_mage_mirror_image.sql
- src/server/game/Spells/Auras/SpellAuraEffects.cpp
- src/server/scripts/Spells/spell_mage.cpp
- src/server/scripts/World/npcs_special.cpp
- src/server/worldserver/worldserver.conf.dist
- Ported mirror image scripts from Ashamane
- Mirror image summons will now display properly
- Mirror image summons will now attack with spell based on player spec
none
tested in-game
none
> Core/Spells: fix mage mirror image display and ai

- sql/updates/world/2024_11_25_refactor_gossip_menu.sql
- sql/updates/world/2024_11_25_separate_gossip_option_mailbox.sql
- src/server/game/AI/ScriptedAI/ScriptedGossip.h
- src/server/game/Conditions/ConditionMgr.cpp
- src/server/game/Entities/Creature/GossipDef.cpp
- src/server/game/Entities/Creature/GossipDef.h
- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Player/Player.h
- src/server/game/Globals/GossipData.cpp
- src/server/game/Globals/GossipData.h
- Refactor `gossip_menu`, `gossip_menu_option`, `gossip_menu_option_locale` tables to be *closer* to AzerothCore (for Keira3 support - see #166 
- Move `GOSSIP_OPTION_MAILBOX` from 18 (`GOSSIP_OPTION_LEARNDUALSPEC`) to 29 (unused) and migrate data
- Disable gossip menu options with type `GOSSIP_OPTION_LEARNDUALSPEC` to help with #178  
Helps with #178
tested in-game
> Core/Gossip: refactor gossip menu tables and separate gossip_option_mailbox

- sql/updates/world/2024_11_25_fix_go_176793_loot.sql
- Fixes loot id for game object 176793 https://www.wowhead.com/object=176793/bundle-of-wood
- Adds `gameobject_loot_template` record for https://www.wowhead.com/item=13872/bundle-of-wood
Closes #179
tested in-game
none
> DB/Loot: fix loot for gameobject 176793

- src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp
* FollowMovementGenerator `NULL` target check
I encountered this crash while doing the Quest: Feeding the Hungry and the Hopeless ( 26271 ) [12]   https://www.wowhead.com/quest=26271
NPC: Homeless Stormwind Citizen ( 42384 ) [10] https://www.wowhead.com/npc=42384 may attempt to follow a `NULL` target, likely when heading to the `Westfall Stew` quest object.
in-game
none
> Core/Movement: FollowMovementGenerator NULL target check

- src/server/game/Entities/Player/Player.cpp
- src/server/game/Entities/Player/Player.h
- src/server/game/Handlers/QuestHandler.cpp
- src/server/game/World/World.cpp
- src/server/scripts/EasternKingdoms/zone_eversong_woods.cpp
- src/server/scripts/Kalimdor/CavernsOfTime/EscapeFromDurnholdeKeep/old_hillsbrad.cpp
- src/server/scripts/Outland/zone_netherstorm.cpp
- src/server/scripts/World/go_scripts.cpp
- src/server/worldserver/worldserver.conf.dist
- Use quest menu with one quest, otherwise use gossip menu
- Add initial support for flag `QUEST_FLAGS_LAUNCH_GOSSIP_ACCEPT`
- Fix some bad default config values (`IgnoreRaid`, `IgnoreAutoAccept`, `IgnoreAutoComplete`)
none
tested in-game
none
> Core/Questing: use quest menu with one quest, otherwise use gossip menu

- src/server/game/Texts/CreatureTextMgr.cpp
- Fixes sound selection logic so `creature_text.sound` is only overridden by `broadcast_text.SoundEntriesID*` when it's non-zero; `creature_text.sound` will still be used when `broadcast_text` has no sound data.
none
tested in-game
none
> Core/CreatureText: fix sound selection logic

- sql/updates/world/2024_11_29_quest_26257.sql
- src/common/Utilities/Timer.h
- src/server/game/AI/CreatureAI.cpp
- src/server/game/AI/CreatureAISelector.cpp
- src/server/game/AI/SmartScripts/SmartAI.cpp
- src/server/game/AI/SmartScripts/SmartAI.h
- src/server/game/Combat/HostileRefManager.cpp
- src/server/game/Combat/HostileRefManager.h
- src/server/game/Combat/ThreatManager.cpp
- src/server/game/Combat/ThreatManager.h
- src/server/game/Combat/UnitEvents.cpp
- src/server/game/Combat/UnitEvents.h
- src/server/game/Entities/Creature/Creature.h
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Entities/Unit/UnitDefines.h
- src/server/game/Maps/MapRefManager.h
- src/server/game/Miscellaneous/SharedDefines.h
- src/server/game/Spells/Auras/SpellAuraEffects.cpp
- src/server/scripts/Commands/cs_npc.cpp
- src/server/scripts/EasternKingdoms/zone_westfall.cpp
- src/server/scripts/Legion/TombOfSargeras/boss_TheDesolateHost.cpp
- src/server/scripts/Spells/spell_generic.cpp
- src/server/shared/Dynamic/LinkedList.h
- src/server/shared/Dynamic/LinkedReference/RefManager.h
- src/server/shared/Dynamic/LinkedReference/Reference.h
- Fixes permanent feign death spells so creatures appear dead in game, e.g. https://www.wowhead.com/npc=42381/overloaded-harvest-golem
- Adds Overloaded Harvest Golem visual effects
- Ref: https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/7f6e63f850aaf71668dedd8394f023eff2ef8452
- Adds spell scripts for entering vehicle, despawning Overloaded Harvest Golem, and Reaping Blows ability
- Ref: https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/445c018e6b6444cfe1cd3b9f7c10ec71f40563af
- Fixes speed change opcode in vehicles (use `SMSG_MOVE_SET_*` instead of `SMSG_MOVE_SPLINE_SET_*`)
- This fixes https://www.wowhead.com/spell=79430/rocket-boost
- Minor threat system update to fix evading
- Ref: …
> Core/Scripts: Quest 26257 It's Alive! - Part 1

- src/server/game/Entities/Player/Player.cpp
* fixed all kinds of stucks inside zones/dungeons/LFG/etc.
* If you enter/exit the same dungeon a few times, you could end up completely jailed inside. Nothing will let you out, not even relogging or restarting.
* this fix will allow you to teleport out of zones/dungeons/LFG
could help with [issue #169](https://github.com/The-Legion-Preservation-Project/LegionCore-7.3.5/issues/169)
tested in-game
- `SetGlobalTeleport` and `IsHasGlobalTeleport` should probably be removed, as there are no such methods in TrinityCore.
> Core/Movement: stuck in teleportation limbo fix

- sql/updates/world/2024_11_30_quest_26290.sql
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Spells/Auras/SpellAuras.cpp
- src/server/game/Spells/Auras/SpellAuras.h
- src/server/game/Spells/SpellScript.cpp
- src/server/game/Spells/SpellScript.h
- src/server/scripts/EasternKingdoms/zone_westfall.cpp
- Adds `DoCheckProc` support to spell scripts
- Ref: https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/89490e4d7f4abff0eb756fcf07fbf21d7ca6381b
- Adds scripts to support sniper fire on [Secrets Of The Tower](https://www.wowhead.com/quest=26290)
- Ref: https://github.com/The-Cataclysm-Preservation-Project/TrinityCore/commit/9abea087e5152a5eb5ba52ad3251a7c55931b3ac
- Disables XP for killing [Mercenary](https://www.wowhead.com/npc=42656)
Closes #191 
tested in-game
none
> Core/Scripts: Quest 26290 Secrets of the Tower

- sql/updates/world/2024_12_01_areatrigger_debug_strings.sql
- sql/updates/world/2024_12_01_quest_26297.sql
- src/server/game/Handlers/MiscHandler.cpp
- src/server/game/Miscellaneous/Language.h
- src/server/scripts/EasternKingdoms/zone_westfall.cpp
- Fix `.debug areatrigger` to show distinct enter/leave messages
- Add AreaTriggerScript to start event for quest [The Dawning Of A New Day](https://www.wowhead.com/quest=26297)
- Adjust event timing
- Play sounds at start and end of event
Closes #193 
tested in-game
none
> Core/Scripts: Fixes for quest 26297 

- src/server/game/Spells/Spell.cpp
- Spell casts should fail when implicit target checks find no valid targets
- This is how TCPP, Ashamane, TC all behave
Closes #188 
tested in-game
none
> Core/Spells: fail spell cast when no implicit nearby targets are found

- src/server/game/Loot/LootMgr.cpp
- Fix a crash caused by encountering certain lootable objects in the world.
LegionCore has a custom loot system where loot items may be currency and have no item id. This caused `LootTemplate::HasQuestDropForPlayer` to crash when encountering objects like [Suspiciously Glowing Chest](https://www.wowhead.com/object=243796).
tested in-game
none
> Core/Loot: fix crash caused by currency loot

- src/server/game/Entities/Creature/Creature.cpp
- src/server/game/Entities/Unit/Unit.cpp
- Fix power type display regression caused by #174 
- Code now matches AshamaneCore
Incorrect power display (100 rage) after #174 
Correct power display (no power display) with this PR:
tested in-game
none
> Core/Creatures: fix power type display regression

- src/server/game/Entities/Creature/GossipDef.cpp
- src/server/game/Entities/Creature/GossipDef.h
- src/server/game/Entities/Player/Player.cpp
- Shows quest discovered popup when looting items that start quests
Closes #207
Closes #192 
tested in-game with a couple items:
- [Tainted Arcane Sliver](https://www.wowhead.com/item=20483)
- [Dirt Stained Scroll](https://www.wowhead.com/item=58898)
none
> Core/Quests: show quest discovery popup when looting items that start quests

- src/server/game/Handlers/QuestHandler.cpp
- src/server/game/Server/Packets/QuestPackets.cpp
- src/server/game/Server/Packets/QuestPackets.h
- src/server/game/Server/Protocol/Opcodes.cpp
- src/server/game/Server/Protocol/Opcodes.h
- src/server/game/Server/WorldSession.h
* unknown packet 0x354D identified
This packet is triggered when completing a quest and accepting the next one "on the go". For example:
* Completing [Canyon Romp](https://www.wowhead.com/quest=26514/canyon-romp) and accepting [They've Wised Up](https://www.wowhead.com/quest=26544/theyve-wised-up) triggers this packet.
tested in-game
- requires a port of the [QuestScript](https://github.com/TrinityCore/TrinityCore/blob/1fb4acc25ae89360e71d33a8f7cba99bcc028b32/src/server/game/Scripting/ScriptMgr.h#L950)(`ScriptMgr`) from TC
> Core/Packets: CMSG_QUEST_GIVER_CLOSE_QUEST implemented

- sql/updates/world/2024_12_02_quest_26520.sql
- src/server/game/Spells/SpellMgr.cpp
- src/server/scripts/EasternKingdoms/zone_redridge_mountains.cpp
- Adds script for [Saving Foreman Oslow](https://www.wowhead.com/quest=26520) quest event
- Adds some waypoints for the town guards
- Ref: https://github.com/TrinityCore/TrinityCore/blob/1fb4acc25ae89360e71d33a8f7cba99bcc028b32/sql/old/7/world/01_2018_02_19/2017_07_04_00_world.sql
- Fixes cast bar and visual for [Control Ettin](https://www.wowhead.com/spell=80704)
- Fixes visibility of some NPCs based on completion of [Saving Foreman Oslow](https://www.wowhead.com/quest=26520)
- Fixes bug with using data from `spell_area` table
- Ref: https://github.com/The-Legion-Preservation-Project/AshamaneCore/commit/0d358200d0ed84cb6269d8fb104276fcb0c7995b
- Removes duplicate ettin creatures
Closes #208 
tested in-game
**Known issues …
> Core/Scripts: Quest 26520 Saving Foreman Oslow

- src/server/game/Entities/Creature/Creature.cpp
- src/server/game/Entities/Unit/Unit.cpp
- src/server/game/Globals/ObjectMgr.cpp
- Fixes creature movement loading to only override default swim (true) when `creature_template_movement` record exists in db
- Ref: https://github.com/TrinityCore/TrinityCore/commit/a91edcb9524b53f027a8ef8c247a443a9bb42f1e
Closes #227 
Closes #228
Closes #229 
tested in-game; confirm `Swim: true` in `.npc info`
- May want to follow up with https://github.com/TrinityCore/TrinityCore/commit/ee620856ad2918ae7ce91a37a980d9f2129a074a
> Core/Movement: fix default creature movement swim

- sql/updates/world/2024_12_04_fix_undead_start.sql
- src/server/game/Spells/SpellInfo.cpp
- Make [Rigor Mortis](https://www.wowhead.com/spell=73523) a buff instead of a debuff
- Auto dismiss [Rigor Mortis](https://www.wowhead.com/spell=73523)
- Ref: https://github.com/TrinityCore/TrinityCore/commit/fc7b6a9e0fac5b0fb36e692eb29671fdbcf9fa4c
none
tested in-game
- Player doesn't always stand up after [Rigor Mortis](https://www.wowhead.com/spell=73523) is dismissed
- Logging out and back in will work around this behavior
- Will create a new issue to track
> DB/Quest: Fix undead start

- src/server/game/Scripting/ScriptMgr.cpp
- These were incorrectly converted as database bound in #240 
Leaving instance group while inside a dungeon will teleport the player out again.
tested in-game
none
> Core/Scripts: fix guild, group, world state script loading
