The-Legion-Preservation-Project/LegionCore-7.3.5

sql/updates/hotfixes/0003_fix_broken_flight_paths.sql
sql/updates/hotfixes/0004_fix_vendor_prices.sql
sql/updates/world/0023_quest_drops_and_creature_corrections.sql
sql/updates/world/0024_more_quest_drops_and_creature_corrections.sql
sql/updates/world/0025_fix_dungeon_levels.sql
sql/updates/world/0026_fix_teleports.sql
sql/updates/world/0027_fix_respawn_times.sql
sql/updates/world/0028_fix_vendor_prices.sql
src/server/game/Globals/ObjectMgr.cpp
src/server/scripts/EasternKingdoms/ScarletHalls/boss_houndmaster_braun.cpp
src/server/scripts/World/npc_taxi.cpp

From https://github.com/SoulSeekkor/LegionCore-7.3.5 at  https://github.com/dufernst/LegionCore-7.3.5/pull/175

lots of quest fixes

---

src/server/game/Entities/Creature/GossipDef.cpp
src/server/game/Entities/Player/KillRewarder.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Miscellaneous/Formulas.h
src/server/game/Miscellaneous/SharedDefines.h
src/server/game/Quests/QuestDef.cpp
src/server/game/Quests/QuestDef.h
src/server/game/Spells/Spell.h
src/server/game/Spells/SpellEffects.cpp

from https://github.com/SoulSeekkor/LegionCore-7.3.5/tree/fix_scaling

quest xp and money scaling

---

sql/updates/characters/0005_character_action_expansion.sql
src/server/game/Entities/Player/CollectionMgr.cpp
src/server/game/Entities/Player/CollectionMgr.h
src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Handlers/MiscHandler.cpp
src/server/game/Handlers/SpellHandler.cpp
src/server/game/Server/Packets/SpellPackets.cpp
src/server/game/Server/Packets/SpellPackets.h

- allows saving random mount button to action bar
- fixes saving favorite mounts to db

fix random mounts

---

.github/workflows/build-win-x64.yml
cmake/compiler/mingw/settings.cmake
cmake/compiler/msvc/settings.cmake
cmake/platform/win/settings.cmake
src/server/worldserver/Main.cpp

from https://github.com/TrinityCore/TrinityCore/blob/4d59558c5604d29807a37ededd7b1ec02d8d9a9e/.github/workflows/win-x64-build.yml

add windows x64 workflow

---

.github/workflows/build-win-x64.yml
src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Unit/Unit.cpp
src/server/game/Handlers/CharacterHandler.cpp
src/server/game/Server/Packets/CharacterPackets.cpp
src/server/game/Server/Packets/CharacterPackets.h
src/server/game/Server/WorldSession.h
src/server/game/Tools/PlayerDump.cpp
src/server/game/World/World.cpp
src/server/game/World/World.h
src/server/scripts/Commands/cs_character.cpp
src/server/worldserver/worldserver.conf.dist

- remove some more strange caching of char enum
- remove DK restrictions, as they weren't present in Legion

char enum and DK fixes

---

src/server/game/Entities/Object/Position.h
src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp
src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.h
src/server/game/Movement/Spline/MoveSpline.h

* Properly synchronize pet's position with its owner.
https://youtu.be/-gkrEeSiSEM

Core/Movement: Rewritten follow movement generator for pets.

---

src/server/game/Entities/Unit/Unit.cpp
src/server/game/Entities/Unit/Unit.h
src/server/game/Movement/MovementGenerators/TargetedMovementGenerator.cpp
src/server/game/Spells/SpellInfo.cpp
src/server/game/Spells/SpellInfo.h

* added some missing methods from TrinityCore

Core/Movement: Pet follow movement code improvements.

---

sql/updates/world/0034_waypoint_move_type.sql
src/server/database/Database/Implementation/WorldDatabase.cpp
src/server/game/Movement/MovementGenerators/WaypointMovementGenerator.cpp
src/server/game/Movement/Waypoints/WaypointManager.cpp
src/server/game/Movement/Waypoints/WaypointManager.h
src/server/scripts/Commands/cs_wp.cpp

https://github.com/TrinityCore/TrinityCore/commit/b5d025938e78ade2033ed2ce23f6ece3a3c27d4d

Core/Movement: allow takeoff and land waypoints

---

src/server/game/Battlefield/BattlefieldMgr.cpp
src/server/game/Battlefield/BattlefieldMgr.h
src/server/game/Globals/ObjectAccessor.cpp
src/server/game/Globals/ObjectAccessor.h
src/server/game/Groups/GroupMgr.cpp
src/server/game/Groups/GroupMgr.h
src/server/game/Loot/LootMgr.cpp
src/server/game/Loot/LootMgr.h
src/server/game/Movement/Waypoints/WaypointManager.cpp
src/server/game/Movement/Waypoints/WaypointManager.h
src/server/game/Pools/PoolMgr.cpp
src/server/game/Pools/PoolMgr.h
src/server/game/Scripting/ScriptMgr.cpp
src/server/game/Scripting/ScriptMgr.h
src/server/game/Spells/SpellMgr.cpp
src/server/game/Spells/SpellMgr.h
src/server/game/Texts/CreatureTextMgr.cpp
src/server/game/Texts/CreatureTextMgr.h
src/server/game/Tickets/TicketMgr.cpp
src/server/game/Tickets/TicketMgr.h
src/server/game/Warden/WardenMgr.cpp
src/server/game/Warden/WardenMgr.h

https://github.com/TrinityCore/TrinityCore/commit/b7f936891aeb86eeb4eb67caa78e672858aa1e20

Core/Game: Move singleton instances into compilation units

---

src/server/game/Entities/Creature/Creature.cpp
src/server/game/Entities/Unit/Unit.cpp

For example, https://www.wowhead.com/npc=40435/headless-ghost

Core/Movement: fix creature hover

---

src/server/game/Guilds/Guild.cpp
src/server/game/Server/WorldSession.cpp
src/server/game/Server/WorldSession.h

- Guild tabard should always be displayed, not just when the session is running.

Core/Guild: Fixed guild tabard displaying in characters list

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Maps/Map.cpp

- Position of Group Member on Map will now sent every 5 Sec.

Core/Group: Fix Group member out of Range

---

src/server/game/Battlegrounds/Battleground.cpp
src/server/game/DataStores/DB2Stores.cpp
src/server/game/Entities/GameObject/GameObject.cpp
src/server/game/Entities/GameObject/GameObjectData.cpp
src/server/game/Garrison/GarrisonFollower.cpp
src/server/game/Garrison/GarrisonMgr.cpp
src/server/game/Globals/BattlePayData.cpp
src/server/game/Globals/ObjectMgr.cpp
src/server/game/GroupFinder/LFGListMgr.cpp
src/server/game/Handlers/QuestHandler.cpp
src/server/game/PetBattle/PetBattle.cpp
src/server/game/Spells/SpellMgr.cpp
src/server/shared/DataStores/DB2DatabaseLoader.h
src/server/shared/DataStores/DB2Store.cpp
src/server/shared/DataStores/DB2Store.h
src/server/shared/DataStores/DBStorageIterator.h

https://github.com/TrinityCore/TrinityCore/commit/ba4c148a696554ad58f6d08ddec8321cdcc8e3c6

Core/DataStores: Devirtualize DB2Storage

---

src/server/game/Entities/Creature/GossipDef.cpp
src/server/game/Entities/Player/Player.cpp
src/server/game/Entities/Player/Player.h
src/server/game/Handlers/QuestHandler.cpp

https://github.com/TrinityCore/TrinityCore/commit/c12ee97f122acfd77bd81cf178a77d5054c312b6 minus the map change stuff.

Core/Player: Rename quest sharing fields

---

src/common/Threading/MPSCQueue.h
src/common/Utilities/MessageBuffer.cpp
src/common/Utilities/MessageBuffer.h
src/server/bnetserver/Server/SessionManager.cpp
src/server/bnetserver/Server/SessionManager.h
src/server/game/Handlers/CharacterHandler.cpp
src/server/game/Server/Packets/AuthenticationPackets.cpp
src/server/game/Server/Packets/AuthenticationPackets.h
src/server/game/Server/Packets/ClientConfigPackets.cpp
src/server/game/Server/Packets/ClientConfigPackets.h
src/server/game/Server/Packets/PacketUtilities.h
src/server/game/Server/Packets/SystemPackets.cpp
src/server/game/Server/WorldSocket.cpp
src/server/game/Server/WorldSocket.h
src/server/game/Server/WorldSocketMgr.cpp
src/server/game/Server/WorldSocketMgr.h
src/server/shared/Networking/AsyncAcceptor.h
src/server/shared/Networking/NetworkThread.h
src/server/shared/Networking/Socket.h
src/server/shared/Networking/SocketMgr.h
src/server/worldserver/Main.cpp

- Fix some packets to match TC 7.3.5
- Use lock-free message buffer
- Port lots of network updates from TC master

Core/Networking: many updates from TC

---

src/server/shared/DataStores/DB2Store.cpp

Core/DataStores: fix db2 localized string

---

sql/updates/world/2024_10_29_smart_script_druid_of_the_fang.sql
src/server/game/AI/ScriptedAI/ScriptedCreature.h
src/server/game/AI/SmartScripts/SmartScript.cpp
src/server/game/AI/SmartScripts/SmartScript.h
src/server/game/AI/SmartScripts/SmartScriptMgr.cpp
src/server/game/AI/SmartScripts/SmartScriptMgr.h
src/server/game/Grids/Notifiers/GridNotifiers.h

From https://github.com/TrinityCore/TrinityCore/commit/8c961687a00970eb7c3f347262e56f0e9a58cf83
Also includes an SAI update for https://www.wowhead.com/npc=3840 to demonstrate; creature will cast healing touch on nearby friendly creatures with low health.

Core/SAI: implement SMART_EVENT_FRIENDLY_HEALTH_PCT

---

src/server/game/Server/Protocol/Opcodes.cpp
src/server/game/Server/Protocol/Opcodes.h

* unknown packet `0x36B6` identified

Core/Packet: CMSG_GET_ACCOUNT_CHARACTER_LIST added

---

src/common/Cryptography/HmacHash.cpp
src/common/Cryptography/HmacHash.h
src/common/Cryptography/OpenSSLCrypto.cpp
src/common/Cryptography/SHA1.cpp
src/common/Cryptography/SHA1.h
src/common/Cryptography/SHA256.cpp
src/common/Cryptography/SHA256.h

-
-
-
Closes #  (insert issue tracker number)
(Does it build, tested in-game, etc.)

Core/Crypto: missing update OpenSSL 3.x

---

src/server/game/Entities/Player/Player.cpp
src/server/game/Loot/LootMgr.cpp
src/server/game/Loot/LootMgr.h

- Fixes regressions to currency loot from https://github.com/The-Legion-Preservation-Project/LegionCore-7.3.5/pull/145
none
- `.additem 152108`
- (open item and see currency successfully added)
none

Core/Loot: fix currency loot

---

src/server/game/AuctionHouse/AuctionHouseMgr.cpp

- When mail is not delayed, the sale pending mail is more annoying than helpful, so skip sending it
none
tested in-game
none

Core/AH: only send sale pending mail when mail is delayed

---

sql/updates/world/2024_11_10_fix_borean_tundra_crash.sql

- `FLEEING_MOTION_TYPE` is not valid for a db entry; this replaces those values with `IDLE_MOTION_TYPE`.
- Fixes crash when loading certain creatures in Borean Tundra
tested in-game
none

DB/Creature: fix crash caused by bad movement type

---

README.md
src/server/database/Updater/DBUpdater.cpp

- Fixes URLs in README.md and DBUpdater after move to GitHub organization
none
none
none

fix issues and release urls

---

src/server/game/AI/CoreAI/CombatAI.cpp
src/server/game/AI/EventMap.cpp
src/server/game/AI/EventMap.h
src/server/scripts/Draenor/Highmaul/boss_imperator_margok.cpp
src/server/scripts/Kalimdor/RagefireChasm/boss_dark_shaman_koranthal.cpp
src/server/scripts/Kalimdor/RagefireChasm/boss_lava_guard_gordoth.cpp
src/server/scripts/Kalimdor/RagefireChasm/boss_slagmaw.cpp
src/server/scripts/Legion/AntorusTheBurningThrone/boss_hasabel.cpp
src/server/scripts/Legion/BlackRookHoldDungeon/boss_illysanna_ravencrest.cpp
src/server/scripts/Legion/BlackRookHoldDungeon/boss_lord_kurtalos_ravencrest.cpp
src/server/scripts/Legion/BlackRookHoldDungeon/boss_smashspite_the_hateful.cpp
src/server/scripts/Northrend/Naxxramas/boss_kelthuzad.cpp
src/server/scripts/Northrend/Ulduar/Ulduar/boss_kologarn.cpp

- Replaced EventMap with version from Ashamane, which will make it easier to port scripts
none
tested in-game
none

Core/AI: upgrade event map

---

sql/updates/world/2024_11_26_quest_176.sql
src/server/scripts/EasternKingdoms/eastern_kingdoms_script_loader.cpp
src/server/scripts/EasternKingdoms/zone_elwynn_forest.cpp

- Fixes https://www.wowhead.com/quest=176/wanted-hogger
- Ported npc scripts from Ashamane
- Ref: https://github.com/The-Legion-Preservation-Project/AshamaneCore/blob/main/src/server/scripts/EasternKingdoms/zone_elwynn_forest.cpp
- Fixed `creature_text` using data from Ashamane DB
Closes #180 
tested in-game
none

Core/Scripts: quest 176 Wanted - Hogger

---

sql/updates/world/2024_11_28_creature_text.sql
src/server/game/Texts/CreatureTextMgr.cpp
src/server/game/Texts/CreatureTextMgr.h

- Rename `creature_text.Entry` column to `creature_text.CreatureID` to help with loading creature text in Keira3
Improves creature text support for #166 
tested in-game
none

DB/Misc: rename creature_text.Entry to creature_text.CreatureID

---

sql/updates/world/2024_12_11_00_creature_text_primary_key.sql
sql/updates/world/2024_12_11_01_auchenai_crypts_trash_ai.sql
src/server/game/Texts/CreatureTextMgr.cpp
src/server/scripts/Outland/Auchindoun/AuchenaiCrypts/boss_exarch_maladaar.cpp

- Ports Auchenai Crypts trash AI based on TC
- Ref: https://github.com/TrinityCore/TrinityCore/commit/c789505019db62eb6cb8d5b4e323dddc2477a1e7
Auchenai Crypts was essentially unplayable with the AI in LC (duplicate spawns and mass summons that never despawn). This should at least make it playable.
tested in-game
- `creature_text` table primary key still differs from TC; will need to fix *a lot* of bad LC data to align PK on this table

DB/SAI: Rework Auchenai Crypts

---

src/common/Utilities/Duration.h

Core/Misc: fix windows builds
